# Generated by Django 2.1.7 on 2019-04-10 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rules', models.CharField(max_length=1024)),
                ('policy', models.CharField(max_length=1024)),
                ('instruction', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Foundation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=128)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Gathering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=128)),
                ('goal', models.CharField(max_length=128)),
                ('time', models.DateField()),
                ('description', models.CharField(max_length=256)),
                ('needed', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Category')),
            ],
        ),
        migrations.CreateModel(
            name='GiveAway',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bags', models.IntegerField(default=1)),
                ('status', models.BooleanField(default=False)),
                ('created', models.DateField(auto_now_add=True)),
                ('archived', models.BooleanField(default=False)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Category')),
                ('foundation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Foundation')),
            ],
        ),
        migrations.CreateModel(
            name='SiteUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=128)),
                ('city', models.CharField(max_length=128)),
                ('postal', models.TextField(max_length=32)),
                ('phone', models.IntegerField()),
                ('date', models.DateField()),
                ('time', models.TimeField(null=True)),
                ('details', models.TextField(blank=True, max_length=256)),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.GiveAway')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='gathering',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.SiteUser'),
        ),
    ]
