# Generated by Django 2.1.7 on 2019-03-27 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190327_1345'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Delivery',
        ),
        migrations.AddField(
            model_name='siteuser',
            name='city',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='siteuser',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='siteuser',
            name='details',
            field=models.TextField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='siteuser',
            name='phone',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='siteuser',
            name='postal',
            field=models.TextField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='siteuser',
            name='street',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='siteuser',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
