# Generated by Django 2.1.7 on 2019-03-27 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190327_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='foundation',
            name='description',
            field=models.CharField(default='opis', max_length=128),
            preserve_default=False,
        ),
    ]
