# Generated by Django 2.1.7 on 2019-03-29 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20190328_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='giveaway',
            name='created',
            field=models.DateField(auto_now_add=True, default='2019-03-29'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='giveaway',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
