# Generated by Django 2.1.7 on 2019-04-01 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20190329_1259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gathering',
            name='count',
        ),
        migrations.RemoveField(
            model_name='giveaway',
            name='count',
        ),
    ]
