# Generated by Django 2.1.7 on 2019-04-01 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20190401_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='giveaway',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
