# Generated by Django 2.1.7 on 2019-04-09 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_giveaway_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gathering',
            name='photo',
            field=models.ImageField(blank=True, upload_to='gathering/'),
        ),
    ]
