# Generated by Django 2.1.7 on 2019-04-09 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20190409_1040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gathering',
            name='photo',
        ),
    ]
